---
language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=1.9.4
  - ANSIBLE_VERSION=2.1.3
  - ANSIBLE_VERSION=latest

before_install:
  - sudo apt-get update -qq

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Syntax check
  - "ansible-playbook -i localhost, test/hitch.yml --syntax-check"

  # Test Hitch
  - "ansible-playbook -i localhost, test/hitch.yml --connection=local --sudo"

  # Idempotency check
  - >
    ansible-playbook -i localhost, test/hitch.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotency: PASS' && exit 0)
    || (echo 'Idempotency: FAIL' && exit 1)

  # Connection test
  - "netstat -ltpn | grep 443 | head -n 1"
  # Facts syntax check
  - >
    sudo cat /etc/ansible/facts.d/hitch.fact
    | python -m json.tool
    && (echo 'Facts syntax: PASS' && exit 0)
    || (echo 'Facts syntax: FAIL' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
