- name: create /etc/hitch/certs/
  file:
    path: /etc/hitch/certs/
    state: directory

- name: Generate a default Self Signed OpenSSL certificate
  openssl_certificate:
    path:  /etc/hitch/certs/default.crt
    privatekey_path: /etc/hitch/certs/default.key
    csr_path: /etc/hitch/certs/default.csr
    provider: selfsigned

- name: Convert default to pem
  shell: cat /etc/hitch/certs/default.key /etc/hitch/certs/default.crt > /etc/hitch/certs/default.pem
  args:
    executable: /bin/bash