- name: Ensure directory exists for local self-signed TLS certs.
  file:
    path: /etc/hitch/certs/
    state: directory

- name: Generate an OpenSSL private key.
  openssl_privatekey:
    path: /etc/hitch/certs/default.key

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: /etc/hitch/certs/default.csr
    privatekey_path: /etc/hitch/certs/default.key
    common_name: "{{ ansible_hostname }}"

- name: Generate a Self Signed OpenSSL certificate.
  openssl_certificate:
    path: /etc/hitch/certs/default.crt
    privatekey_path: /etc/hitch/certs/default.key
    csr_path: /etc/hitch/certs/default.csr
    provider: selfsigned

- name: Convert default to pem
  shell: cat /etc/hitch/certs/default.key /etc/hitch/certs/default.crt > /etc/hitch/certs/default.pem
  args:
    executable: /bin/bash