---
- name: install debian dependencies
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
    state: present
  with_items:
    - gcc
    - make
    - libev-dev
    - libssl-dev
    - automake
    - python-docutils
    - flex
    - bison
    - pkg-config
    # This should be `else omit`, but it fails on Ansible 1.x, so just duplicate gcc
    - "{{ 'libc6-dev-i386' if redis_make_32bit|bool else 'gcc' }}"
  when: ansible_os_family == "Debian"
