---

# get_url on Ansible 1.x only supports sha256 checksumming, so we're only
# using `checksums` on Ansible 2.x because they're sha1.
- name: set hitch checksum
  set_fact:
    checksum: "{{ 'sha1' if checksums[version]|length == 40 else 'sha256' }}:{{ checksums[version] }}"
  when:
    - verify_checksum|bool
    - checksum is not defined
    - version in checksums
    - ansible_version.major >= 2

- name: download hitch (ansible 1.x)
  get_url:
    url: "{{ download_url }}"
    dest: /usr/local/src/hitch-{{ version }}.tar.gz
    sha256sum: "{{ checksum|default(omit) }}"
  when:
    - not tarball
    - ansible_version.major < 2

- name: download hitch (ansible 2.x)
  get_url:
    url: "{{ download_url }}"
    dest: /usr/local/src/hitch-{{ version }}.tar.gz
    checksum: "{{ checksum|default(omit) }}"
  when:
    - not tarball
    - ansible_version.major >= 2

- name: upload hitch
  copy:
    src: "{{ tarball }}"
    dest: /usr/local/src/hitch-{{ version }}.tar.gz
  when: tarball|default(false)

- name: extract hitch tarball
  unarchive:
    src: /usr/local/src/hitch-{{ version }}.tar.gz
    dest: /usr/local/src
    creates: /usr/local/src/hitch-{{ version }}/Makefile
    copy: no
