---
- include: check_vars.yml

- include: download.yml
  tags:
    - download

- include: dependencies.yml
  tags:
    - install

- include: install.yml
  tags:
    - install

- include: certificates.yml
  tags:
    - certs

- include: hitch.yml
  tags:
    - config

- include: local_facts.yml
  when: local_facts|bool
